
class DCX_PlayerbotSpawner : LevelPostProcessor 
{
		protected void Apply(Name checksum, String mapname)
		{
			for (int i = 0; i < GetThingCount(); i++)
			{
				let flags = GetThingFlags(i);
				int ednum = GetThingEdNum(i);
				String mapPrefix = level.MapName.Left(6);
				mapPrefix = mapPrefix.MakeLower();
				String mapName = level.MapName.MakeLower();
				
					if ( mapName.Left(6) == "fd_dmm" )
					{
						if (ednum == 11)
						SetThingEdNum(i, 7734); 
					}			 
				}
			}
}